### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined in connection/base.js

### ISSUE THREAD

**Issue by VikramTiwari** [LearnBoost/mongoose#2757] opened 2015-03-12 11:51 UTC
```
/Users/vikram/Documents/code/SilverPush/falcon/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;      
              ^
TypeError: Cannot read property 'length' of undefined
    at processResults (/Users/vikram/Documents/code/SilverPush/falcon/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1581:31)
    at /Users/vikram/Documents/code/SilverPush/falcon/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1619:20
    at /Users/vikram/Documents/code/SilverPush/falcon/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1157:7
    at /Users/vikram/Documents/code/SilverPush/falcon/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1890:9
    at Server.Base._callHandler (/Users/vikram/Documents/code/SilverPush/falcon/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:448:41)
    at /Users/vikram/Documents/code/SilverPush/falcon/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:481:18
    at MongoReply.parseBody (/Users/vikram/Documents/code/SilverPush/falcon/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/Users/vikram/Documents/code/SilverPush/falcon/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:439:20)
    at emit (events.js:107:17)
    at null.<anonymous> (/Users/vikram/Documents/code/SilverPush/falcon/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
```

**Comment by steve-p-com** [comment] 2015-03-12 12:47
I believe this is a duplicate of https://github.com/LearnBoost/mongoose/issues/2587 which may well have been fixed, but so far has not made it into the 3.8.x release. I also had this problem today.

**Comment by vkarpov15** [comment] 2015-03-12 13:01
Actually #2587 has made it into 3.8.x, it's been in since 3.8.22. What version of mongoose are you using?

**Comment by steve-p-com** [comment] 2015-03-12 13:12
You're right. I had a mongoose dependency which I thought said "^3.8.20" but actually it said "3.8.20". I must need my eyes testing.

**Comment by vkarpov15** [comment] 2015-03-12 13:19
Happens :) I generally like to specify exact version numbers in package.json to avoid such issues.

**Closed by vkarpov15** 2015-03-12 13:19 UTC

**Comment by VikramTiwari** [comment] 2015-03-12 14:57
Thanks guys! Updating to newer version fixed it. :+1:

**Comment by nabulaer** [comment] 2015-03-26 09:25
This bug came back on 3.9.7

**Comment by anfield6road** [comment] 2015-03-26 10:07
correct, back in 3.9.7 and seems to be fixed again in 4.0.0

**Comment by rjbergerud** [comment] 2015-03-26 20:11
I have the same problem and I've updated to 4.0.0:

/home/ec2-user/brandanalysis/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;
              ^
TypeError: Cannot read property 'length' of undefined
    at processResults (/home/ec2-user/brandanalysis/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1581:31)
    at /home/ec2-user/brandanalysis/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1619:20
    at /home/ec2-user/brandanalysis/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1157:7
    at /home/ec2-user/brandanalysis/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1890:9
    at Server.Base._callHandler (/home/ec2-user/brandanalysis/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:448:41)
    at /home/ec2-user/brandanalysis/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:481:18
    at MongoReply.parseBody (/home/ec2-user/brandanalysis/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/home/ec2-user/brandanalysis/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:439:20)
    at emit (events.js:109:17)
    at null.<anonymous> (/home/ec2-user/brandanalysis/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)

**Comment by vkarpov15** [comment] 2015-03-26 20:21
@rjbergerud can you show me how you're connecting?

**Comment by rjbergerud** [comment] 2015-03-26 20:38
//Just using localhost on port 27017
mongoose.connect('mongodb://localhost/brands');

I've downgraded to 3.8.21 and stopped getting the error.

**Comment by rjbergerud** [comment] 2015-03-26 21:09
Sorry, it turns out I have issues with both versions.

**Comment by vkarpov15** [comment] 2015-03-26 21:27
Hmm so the stack trace you posted above definitely is not from mongoose 4.0.0. Mongoose 4 uses node driver v2.x, which doesn't have a `mongodb/lib/mongodb/db.js` file, or a `mongodb/lib/mongodb` directory for that matter. Can you double check the version for me?

**Comment by rjbergerud** [comment] 2015-03-26 22:16
You're right, for some reason, npm view mongoose version was returning a different version than was listed in package.json inside the mongoose modules

**Comment by cyvirus** [comment] 2015-03-27 08:42
I have same problem.
Same code, but something it run well, something it occur error.
I tested with mongoose v3.9.7

**Comment by vkarpov15** [comment] 2015-03-27 13:47
3.9.7 is obsolete, use 4.0.0 instead

**Comment by mrchess** [comment] 2015-05-16 04:20
I ran into this same issue at 4.0.0 fixed it for me.

**Comment by qqxufo** [comment] 2016-05-03 03:53
Thx, fixed by 4.0.0

**Comment by zulbil** [comment] 2016-08-17 03:57
I have the same problem. I tried to update mongoose but nothing works. I'm using mongoose 4.5.9 the latest version. I have the following error: 
 PS C:\node\NodeProjects\retailApp\myApp> node .\index.js
C:\node\NodeProjects\retailApp\myApp\node_modules\mongoose\lib\index.js:441
  for (i = 0, len = schema.childSchemas.length; i < len; ++i) {
                                       ^

TypeError: Cannot read property 'length' of undefined
    at Mongoose._applyPlugins (C:\node\NodeProjects\retailApp\myApp\node_modules\mongoose\lib\index.js:441:40)
    at Mongoose.model (C:\node\NodeProjects\retailApp\myApp\node_modules\mongoose\lib\index.js:347:12)
    at module.exports (C:\node\NodeProjects\retailApp\myApp\models.js:11:11)
    at Object.<anonymous> (C:\node\NodeProjects\retailApp\myApp\index.js:4:20)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by kog13** [comment] 2016-09-06 22:58
@zulbil experienced this error as well, occurred when adding a single embedded document via a plugin, childSchemas was undefined.

**Comment by tramel-woodard** [comment] 2016-11-02 17:11
Adding my two cents for posterity (seeing I found this thread due to the same issue).

All issues resolved after an update from 3.8.15 to 4.0.0.

**Comment by dpinart** [comment] 2016-11-03 21:09
I'm facing this same issue with the latest version (4.6.5). It's a weird issue as a I'm getting this error since I've upgraded to nodejs 4.9.1 and npm 3.10.8. It seems the issue is related to the flatten dependency resolution introduced by npm v3. I have copied the node_modules from a labtop with npm v2 to my labtop and the issue was fixed.

**Comment by dpinart** [comment] 2016-11-03 22:58
Hi
My apologizes. Nothing related with npm v3. Downgrading to mongoose 4.4.12 fixes the issue. It seems the issue is localized at Mongoose.prototype._applyPlugins method. In version 4.6.5 it looks like if the schema defines a hierarchy and the exceptions is raised when trying to iterate over the childSchemas collection

**Comment by vkarpov15** [comment] 2016-11-09 17:06
Please provide a code sample @dpinart

**Comment by mohamedmorsi1993** [comment] 2019-09-07 13:12
i have the same promblem
TypeError: Cannot read property 'length' of undefined
i think that is happens when i try to access an array on schema object i can retrieve data from every where else
and that is happens when i connect mongoose to the local mongo server it works fine when i connect mongoose to cluster
