### ISSUE TITLE
`select` does not backfill default values

### ISSUE THREAD

**Issue by boblauer** [LearnBoost/mongoose#2670] opened 2015-02-11 23:07 UTC
When `select`ing a property, it's default values are not populated.

Simple example to describe the issue:

Schema:
```javascript
var UserSchema = new Schema({
  name: String,
  personal: {
    age: { type: Number, default: 21 },
    maritalStatus: { type: String, default: 'single' }
  }
};
```

We have a record in the database of the form:
```javascript
{
  _id: '123'
  name: 'John Doe'
}
```

```
User.findById('123').exec(function(err, user) {
  console.log(user.personal) // { age: 21, maritalStatus: 'single' }
});

User.findById('123').select('personal').exec(function(err, user) {
  console.log(user.personal) // {}
});
```

**Comment by vkarpov15** [comment] 2015-02-12 16:11
Thanks for pointing this out, I'll look into it.

**Comment by vkarpov15** [comment] 2015-02-23 20:25
This is a duplicate of #2629 as far as I can tell.

**Closed** 2015-02-23 21:53 UTC
