### ISSUE TITLE
findOneAndUpdate (and other methods) should allow strict option

### ISSUE THREAD

**Issue by dillonkrug** [LearnBoost/mongoose#1967] opened 2014-03-19 22:13 UTC
Because of #1947 the following 'update' doesn't actually change anything:

```javascript
Model.findOneAndUpdate({
    _id: 'xxxxxxxxxxxxxxxxxxxxxxxx'
}, {
    $pull: {
        field: {
            $or: [
                { name: 'thing'  }, 
                { other: { $gt: 5 } }
            ]
        }
    }
})
```

I thought I'd resolved this case by adding the option `{ strict: false }` but that didn't work.

It appears to be because the 'strict' option is only available with `Model.update()`

It seems to make sense that it should work with `findOneAndUpdate` as well.

**Comment by lancespeelmon** [comment] 2015-02-04 00:03
FYI - this issue is causing me pain as well. :japanese_goblin:

**Comment by vkarpov15** [comment] 2015-02-04 20:00
Duplicate of #1932. Solution is to upgrade to 3.8.15.

**Comment by dillonkrug** [comment] 2015-02-04 20:12
The "goal" of this ticket was to allow findOneAndUpdate to take `strict: false` as an option. is this now possible?

I just checked the [docs](http://mongoosejs.com/docs/api.html#query_Query-findOneAndUpdate) which indicate nothing has changed.

For the given use case, 3.8.15 solves the original problem.  But it still doesn't make a ton of sense that `update()` can be non-strict, but `findOneAndUpdate()` cannot.

**Comment by vkarpov15** [comment] 2015-02-05 16:28
Ah ok I see what you mean. I'll reopen this. Thanks.

**Closed** 2015-02-20 19:35 UTC
